---
# Supplementary configuration file
- name: max-open-files | Create folder
  file:
    path: "/etc/systemd/system/mariadb.service.d"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rx,o=rx"
  notify: "reload systemd daemon"
  become: true

- name: max-open-files | Add the overriding file
  template:
    src: "etc/systemd/system/mariadb.service.d/max-open-files.conf.j2"
    dest: "/etc/systemd/system/mariadb.service.d/max-open-files.conf"
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"
  notify: "reload systemd daemon"
  become: true
