---

- name: "Check if {{ mariadb_sst_username }} exists in the system"
  block:
    - name: "Check if {{ mariadb_sst_username }} exists in the system"
      getent:
        database: passwd
        key: "{{ mariadb_sst_username }}"
      ignore_errors: true
      register: mariadb_sst_username__found
    - name: Fail if the above user does not exist
      fail:
        msg: >-
          The plugin for mariadb_sst_username was
          set to unix_socket but the user does not exist.
      when: mariadb_sst_username__found.failed
  delegate_to: "{{ galera_mysql_first_node }}"
  run_once: true
  when: mariadb_sst_user_plugin == "unix_socket"

- name: Create definition for mariadb_sst_user via unix_socket
  set_fact:
    mariadb_sst_user:
      - name: "{{ mariadb_sst_username }}"
        hosts: "localhost"
        plugin: "{{ mariadb_sst_user_plugin }}"
        priv: "*.*:RELOAD,PROCESS,LOCK TABLES,BINLOG MONITOR"
  delegate_to: "{{ galera_mysql_first_node }}"
  run_once: true
  when: mariadb_sst_user_plugin == "unix_socket"

- name: Create definition for mariadb_sst_user via mysql_native_password
  set_fact:
    mariadb_sst_user:
      - name: "{{ mariadb_sst_username }}"
        hosts: "localhost"
        password: "{{ mariadb_sst_password }}"
        priv: "*.*:RELOAD,PROCESS,LOCK TABLES,BINLOG MONITOR"
  delegate_to: "{{ galera_mysql_first_node }}"
  run_once: true
  when: mariadb_sst_user_plugin == "mysql_native_password"

- name: mysql_users | create MySQL users
  mysql_user:
    append_privs: "{{ item.0.append_privs | default('no') }}"
    encrypted: "{{ item.0.encrypted | default('no') }}"
    host: "{{ item.1 }}"
    login_unix_socket: "{{ mariadb_login_unix_socket | default(omit) }}"
    name: "{{ item.0.name }}"
    password: "{{ item.0.password | default(omit) }}"
    plugin: "{{ item.0.plugin | default(omit) }}"
    plugin_auth_string: "{{ item.0.plugin_auth_string | default(omit) }}"
    plugin_hash_string: "{{ item.0.plugin_hash_string | default(omit) }}"
    tls_requires: "{{ item.0.tls_requires | default(omit) }}"
    priv: "{{ item.0.priv | default('*.*:USAGE') }}"
    state: "{{ item.0.state | default('present') }}"
  become: true
  no_log: true
  delegate_to: "{{ galera_mysql_first_node }}"
  run_once: true
  with_subelements:
    - "{{ (galera_sst_method == 'mariabackup') | ternary( mariadb_mysql_users | union( mariadb_sst_user ), mariadb_mysql_users ) }}"
    - "hosts"
